spring.application.name=mercado

spring.datasource.url=jdbc:postgresql://localhost:5432/mercado
spring.datasource.username=postgres
spring.datasource.password=JUjub4h100.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.docker.compose.enabled=false
server.port=8082
