export const resourceConfigs = {
  produtos: {
    title: "Produtos",
    eyebrow: "Catálogo administrativo",
    description: "Cadastre, altere e retire itens disponíveis no catálogo público.",
    singular: "produto",
    endpoint: "/api/produtos",
    idKey: "codigo",
    canEdit: true,
    accent: "mint",
    fields: [
      { name: "nome", label: "Nome", placeholder: "Ex.: Arroz 5 kg", required: true },
      { name: "marca", label: "Marca", placeholder: "Ex.: Tio João" },
      { name: "preco", label: "Preço", type: "number", step: "0.01", min: "0.01", required: true, numeric: true },
      { name: "codigoBarras", label: "Código de barras", placeholder: "Ex.: 7890000000000" },
      { name: "validade", label: "Validade", type: "date" },
      { name: "descricao", label: "Descrição", placeholder: "Informações úteis sobre o produto", wide: true },
    ],
    columns: [
      { key: "codigo", label: "Código", format: "code" },
      { key: "nome", label: "Produto" },
      { key: "marca", label: "Marca" },
      { key: "preco", label: "Preço", format: "currency" },
      { key: "validade", label: "Validade", format: "date" },
    ],
  },
  clientes: {
    title: "Clientes",
    eyebrow: "Relacionamento",
    description: "Mantenha os contatos dos clientes organizados para um atendimento mais próximo.",
    singular: "cliente",
    endpoint: "/api/clientes",
    idKey: "id",
    canEdit: true,
    accent: "peach",
    fields: [
      { name: "nome", label: "Nome completo", required: true },
      { name: "cpf", label: "CPF", placeholder: "000.000.000-00" },
      { name: "telefone", label: "Telefone", placeholder: "(00) 00000-0000" },
      { name: "email", label: "E-mail", type: "email" },
      { name: "endereco", label: "Endereço", wide: true },
    ],
    columns: [
      { key: "id", label: "Código", format: "code" },
      { key: "nome", label: "Cliente" },
      { key: "telefone", label: "Telefone" },
      { key: "email", label: "E-mail" },
    ],
  },
  fornecedores: {
    title: "Fornecedores",
    eyebrow: "Compras e reposição",
    description: "Centralize os contatos de quem abastece as prateleiras do mercadinho.",
    singular: "fornecedor",
    endpoint: "/api/fornecedores",
    idKey: "id",
    canEdit: true,
    accent: "butter",
    fields: [
      { name: "nome", label: "Nome ou razão social", required: true },
      { name: "cnpj", label: "CNPJ", placeholder: "00.000.000/0000-00" },
      { name: "telefone", label: "Telefone" },
      { name: "email", label: "E-mail", type: "email" },
      { name: "endereco", label: "Endereço", wide: true },
    ],
    columns: [
      { key: "id", label: "Código", format: "code" },
      { key: "nome", label: "Fornecedor" },
      { key: "cnpj", label: "CNPJ" },
      { key: "telefone", label: "Telefone" },
      { key: "email", label: "E-mail" },
    ],
  },
  funcionarios: {
    title: "Equipe",
    eyebrow: "Acessos administrativos",
    description: "Cadastre funcionários e defina quem pode acessar a administração.",
    singular: "funcionário",
    endpoint: "/api/funcionarios",
    idKey: "id",
    accent: "mint",
    fields: [
      { name: "nome", label: "Nome completo", required: true },
      { name: "cpf", label: "CPF", placeholder: "000.000.000-00" },
      { name: "telefone", label: "Telefone" },
      { name: "email", label: "E-mail de acesso", type: "email", required: true },
      { name: "cargo", label: "Cargo", type: "select", required: true, options: ["Administrador", "Gerente", "Caixa", "Estoquista", "Atendente"] },
      { name: "salario", label: "Salário", type: "number", step: "0.01", min: "0", numeric: true },
      { name: "senha", label: "Senha", type: "password", required: true, wide: true },
    ],
    columns: [
      { key: "id", label: "Código", format: "code" },
      { key: "nome", label: "Funcionário" },
      { key: "cargo", label: "Cargo", format: "status" },
      { key: "email", label: "E-mail" },
      { key: "salario", label: "Salário", format: "currency" },
    ],
  },
  estoques: {
    title: "Estoque",
    eyebrow: "Controle de quantidades",
    description: "Registre os níveis disponíveis e identifique reposições necessárias.",
    singular: "registro de estoque",
    endpoint: "/api/estoques",
    idKey: "id",
    accent: "mint",
    fields: [
      { name: "quantidadeDisponivel", label: "Quantidade disponível", type: "number", min: "0", required: true, numeric: true },
      { name: "estoqueMinimo", label: "Estoque mínimo", type: "number", min: "0", required: true, numeric: true },
      { name: "estoqueMaximo", label: "Estoque máximo", type: "number", min: "0", required: true, numeric: true },
      { name: "dataAtualizacao", label: "Data da atualização", type: "datetime-local", required: true, wide: true },
    ],
    columns: [
      { key: "id", label: "Código", format: "code" },
      { key: "quantidadeDisponivel", label: "Disponível" },
      { key: "estoqueMinimo", label: "Mínimo" },
      { key: "estoqueMaximo", label: "Máximo" },
      { key: "dataAtualizacao", label: "Atualização", format: "dateTime" },
    ],
  },
  lotes: {
    title: "Lotes",
    eyebrow: "Entrada de mercadorias",
    description: "Acompanhe origem, quantidade, custo e validade das mercadorias recebidas.",
    singular: "lote",
    endpoint: "/api/lotes",
    idKey: "id",
    accent: "butter",
    fields: [
      { name: "categoriaDoProduto", label: "Categoria", required: true },
      { name: "marcaDoProduto", label: "Marca", required: true },
      { name: "quantidade", label: "Quantidade", type: "number", min: "1", required: true, numeric: true },
      { name: "codigo", label: "Código do produto", type: "number", min: "1", required: true, numeric: true },
      { name: "valorTotalDoLote", label: "Valor total", type: "number", step: "0.01", min: "0", required: true, numeric: true },
      { name: "fabricacao", label: "Fabricação", type: "date" },
      { name: "validade", label: "Validade", type: "date", wide: true },
    ],
    columns: [
      { key: "id", label: "Lote", format: "code" },
      { key: "categoriaDoProduto", label: "Categoria" },
      { key: "marcaDoProduto", label: "Marca" },
      { key: "quantidade", label: "Quantidade" },
      { key: "valorTotalDoLote", label: "Valor", format: "currency" },
      { key: "validade", label: "Validade", format: "date" },
    ],
  },
  caixas: {
    title: "Caixas",
    eyebrow: "Abertura e fechamento",
    description: "Registre os saldos e horários de cada período de funcionamento do caixa.",
    singular: "caixa",
    endpoint: "/api/caixas",
    idKey: "id",
    accent: "peach",
    fields: [
      { name: "saldoInicial", label: "Saldo inicial", type: "number", step: "0.01", min: "0", required: true, numeric: true },
      { name: "saldoFinal", label: "Saldo final", type: "number", step: "0.01", min: "0", numeric: true },
      { name: "dataAbertura", label: "Abertura", type: "datetime-local", required: true },
      { name: "dataFechamento", label: "Fechamento", type: "datetime-local" },
    ],
    columns: [
      { key: "id", label: "Caixa", format: "code" },
      { key: "saldoInicial", label: "Saldo inicial", format: "currency" },
      { key: "saldoFinal", label: "Saldo final", format: "currency" },
      { key: "dataAbertura", label: "Abertura", format: "dateTime" },
      { key: "dataFechamento", label: "Fechamento", format: "dateTime" },
    ],
  },
  pagamentos: {
    title: "Pagamentos",
    eyebrow: "Movimentação do caixa",
    description: "Registre as formas de pagamento, os valores recebidos e o troco.",
    singular: "pagamento",
    endpoint: "/api/pagamentos",
    idKey: "id",
    accent: "butter",
    fields: [
      { name: "tipoPagamento", label: "Forma de pagamento", type: "select", required: true, options: ["Dinheiro", "Pix", "Cartão de débito", "Cartão de crédito"] },
      { name: "valorPago", label: "Valor pago", type: "number", step: "0.01", min: "0", required: true, numeric: true },
      { name: "troco", label: "Troco", type: "number", step: "0.01", min: "0", numeric: true },
      { name: "status", label: "Status", type: "select", required: true, options: ["Aprovado", "Pendente", "Cancelado"] },
      { name: "dataPagamento", label: "Data do pagamento", type: "datetime-local", required: true, wide: true },
    ],
    columns: [
      { key: "id", label: "Código", format: "code" },
      { key: "tipoPagamento", label: "Forma" },
      { key: "valorPago", label: "Valor", format: "currency" },
      { key: "troco", label: "Troco", format: "currency" },
      { key: "status", label: "Status", format: "status" },
      { key: "dataPagamento", label: "Data", format: "dateTime" },
    ],
  },
  financeiros: {
    title: "Financeiro",
    eyebrow: "Receitas e despesas",
    description: "Acompanhe entradas, saídas e o resultado financeiro de cada registro.",
    singular: "registro financeiro",
    endpoint: "/api/financeiros",
    idKey: "id",
    accent: "mint",
    fields: [
      { name: "receita", label: "Receita", type: "number", step: "0.01", min: "0", required: true, numeric: true },
      { name: "despesa", label: "Despesa", type: "number", step: "0.01", min: "0", required: true, numeric: true },
      { name: "lucro", label: "Lucro", type: "number", step: "0.01", required: true, numeric: true },
      { name: "dataRegistro", label: "Data do registro", type: "date", required: true, wide: true },
    ],
    columns: [
      { key: "id", label: "Código", format: "code" },
      { key: "receita", label: "Receita", format: "currency" },
      { key: "despesa", label: "Despesa", format: "currency" },
      { key: "lucro", label: "Lucro", format: "currency" },
      { key: "dataRegistro", label: "Data", format: "date" },
    ],
  },
  mercados: {
    title: "Dados do mercado",
    eyebrow: "Informações do estabelecimento",
    description: "Mantenha endereço, contato e horário de funcionamento atualizados.",
    singular: "mercado",
    endpoint: "/api/mercados",
    idKey: "id",
    accent: "peach",
    fields: [
      { name: "nome", label: "Nome", required: true },
      { name: "cnpj", label: "CNPJ" },
      { name: "telefone", label: "Telefone" },
      { name: "email", label: "E-mail", type: "email" },
      { name: "endereco", label: "Endereço", wide: true },
      { name: "horarioFuncionamento", label: "Horário de funcionamento", placeholder: "Ex.: Segunda a sábado, 7h às 20h", wide: true },
    ],
    columns: [
      { key: "id", label: "Código", format: "code" },
      { key: "nome", label: "Mercado" },
      { key: "cnpj", label: "CNPJ" },
      { key: "telefone", label: "Telefone" },
      { key: "horarioFuncionamento", label: "Funcionamento" },
    ],
  },
};
